name: CI

on:
  push:
    branches: [main]

env:
  CI: true
  NODE_VERSION: 16

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'aws-actions/configure-aws-credentials@v1'
        with:
          role-to-assume: arn:aws:iam::463151931555:role/github-action
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: ./.github/actions/sls-mentor
  