name: CI

on:
  push:
    branches: [main]

env:
  CI: true
  NODE_VERSION: 16

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/sls-mentor
  